# Generated by Django 5.1.1 on 2024-10-27 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookself', '0003_rename_userprofile_userprofil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofil',
            name='is_confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
