# Generated by Django 5.1.1 on 2024-10-27 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookself', '0004_alter_userprofil_is_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofil',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
